repos:
  - repo: local
    hooks:
      - id: fix
        name: auto-fix
        entry: make fix
        language: system
        pass_filenames: false
        always_run: true

      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
